export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_PRODUCTS_SUCCEEDED = "GET_PRODUCTS_SUCCEEDED"
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED"

export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL"
export const GET_PRODUCT_DETAIL_SUCCEEDED = "GET_PRODUCT_DETAIL_SUCCEEDED"
export const GET_PRODUCT_DETAIL_FAILED = "GET_PRODUCT_DETAIL_FAILED"